<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>hits2025_java_missed-classes</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>hits2025_java_missed-classes</name>
    <description>Backend for a common project. Accounting for missed classes.</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <!--&lt;!&ndash;		<dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;			<groupId>org.springframework.boot</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;			<artifactId>spring-boot-starter-data-jdbc</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;		</dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;		2&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.springframework.boot</groupId>-->
        <!--			<artifactId>spring-boot-starter-data-jpa</artifactId>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		<dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;			<groupId>org.springframework.boot</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;			<artifactId>spring-boot-starter-jdbc</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;		</dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;		1&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.springframework.boot</groupId>-->
        <!--			<artifactId>spring-boot-starter-web</artifactId>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		7&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.springdoc</groupId>-->
        <!--			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>-->
        <!--			<version>2.2.0</version>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		8&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.springframework.boot</groupId>-->
        <!--			<artifactId>spring-boot-starter-security</artifactId>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		9&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>io.jsonwebtoken</groupId>-->
        <!--			<artifactId>jjwt-api</artifactId>-->
        <!--			<version>0.11.5</version>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		10&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>io.jsonwebtoken</groupId>-->
        <!--			<artifactId>jjwt-impl</artifactId>-->
        <!--			<version>0.11.5</version>-->
        <!--			<scope>runtime</scope>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		11&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>io.jsonwebtoken</groupId>-->
        <!--			<artifactId>jjwt-jackson</artifactId>-->
        <!--			<version>0.11.5</version>-->
        <!--			<scope>runtime</scope>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		<dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;			<groupId>javax.xml.bind</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;			<artifactId>jaxb-api</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;			<version>2.3.1</version>&ndash;&gt;-->
        <!--&lt;!&ndash;		</dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;		<dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;			<groupId>io.swagger.core.v3</groupId>&ndash;&gt;-->
        <!--&lt;!&ndash;			<artifactId>swagger-annotations</artifactId>&ndash;&gt;-->
        <!--&lt;!&ndash;			<version>2.2.15</version>&ndash;&gt;-->
        <!--&lt;!&ndash;		</dependency>&ndash;&gt;-->
        <!--&lt;!&ndash;		3&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>com.h2database</groupId>-->
        <!--			<artifactId>h2</artifactId>-->
        <!--			<scope>runtime</scope>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		4&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.postgresql</groupId>-->
        <!--			<artifactId>postgresql</artifactId>-->
        <!--			<scope>runtime</scope>-->
        <!--		</dependency>-->
        <!--		&lt;!&ndash; 5 &ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.springframework.boot</groupId>-->
        <!--			<artifactId>spring-boot-starter-validation</artifactId>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		6&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.apache.commons</groupId>-->
        <!--			<artifactId>commons-lang3</artifactId>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		12&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.projectlombok</groupId>-->
        <!--			<artifactId>lombok</artifactId>-->
        <!--			<optional>true</optional>-->
        <!--		</dependency>-->
        <!--&lt;!&ndash;		11&ndash;&gt;-->
        <!--		<dependency>-->
        <!--			<groupId>org.springframework.boot</groupId>-->
        <!--			<artifactId>spring-boot-starter-test</artifactId>-->
        <!--			<scope>test</scope>-->
        <!--		</dependency>-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- База данных -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Утилиты -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.2.0</version>
        </dependency>

        <!-- Безопасность -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.11.5</version>
        </dependency>

        <!-- Тестирование -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
